bloGrid/Models/Account.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace bloGrid.Models
{
    public class Account
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string layoutJSON { get; set; }
    }

    public class AccountDBContext : DbContext
    {
        public DbSet<Account> Accounts { get; set; }
    }
}

bloGrid/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bloGrid.Controllers
{
    public class ErrorController : Controller
    {
        //
        // GET: /Error/

        public ActionResult FailWhale()
        {
            Response.StatusCode = 404;
            Response.TrySkipIisCustomErrors = true;
            return View();
        }

    }
}

bloGrid/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using bloGrid.Models;
using System.Security.Cryptography;

namespace bloGrid.Controllers
{
    public class HomeController : Controller
    {
        

        public ActionResult Index()
        {
            var db = new AccountDBContext();
            Account acc = db.Accounts.Where(p => p.Name == "blog").FirstOrDefault();
            JavaScriptSerializer marshal = new JavaScriptSerializer();
            ViewBag.Panels = marshal.Deserialize<List<Dictionary<string, string>>>(acc.layoutJSON);
            //ViewBag.Panels = ParsedJsonMockup.getMockup();
            return View();
        }

        public ActionResult Delete()
        {
            var db = new AccountDBContext();
            Account acc = db.Accounts.Where(p => p.Name == "blog").FirstOrDefault();
            JavaScriptSerializer marshal = new JavaScriptSerializer();
            var clear = new List<Dictionary<string, string>>();
            string emptyJson = marshal.Serialize(clear);
            acc.layoutJSON = emptyJson;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Account acc)
        {
            var db = new AccountDBContext();
            Account blog = db.Accounts.Where(p => p.Name == "blog").FirstOrDefault();
            string name = acc.Name;
            string pass = acc.Password;
            if (name == "blog")
            {
                if (Hashing.VerifyMd5Hash(MD5.Create(), pass, blog.Password) == true)
                {
                    ViewBag.Logged = true;
                }
            }
            JavaScriptSerializer marshal = new JavaScriptSerializer();
            ViewBag.Panels = marshal.Deserialize<List<Dictionary<string, string>>>(blog.layoutJSON);
            return View("Index");
        }

        [HttpGet]
        public ActionResult NewPanel(string q)
        {
            var db = new AccountDBContext();
            Account acc = db.Accounts.Where(p => p.Name == "blog").FirstOrDefault();
            JavaScriptSerializer marshal = new JavaScriptSerializer();
            ViewBag.Panels = marshal.Deserialize<List<Dictionary<string, string>>>(acc.layoutJSON);
            if (q != null)
            {
                var dict = marshal.Deserialize<Dictionary<string, string>>(q);
                ViewBag.Panels.Add(dict);
                string newJson = marshal.Serialize(ViewBag.Panels);
                acc.layoutJSON = newJson;
                db.SaveChanges();
            }
            return View("Index");
        }

    }
}

bloGrid/Controllers/StyleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bloGrid.Controllers
{
    public class StyleController : Controller
    {
        public string Index()
        {
            /*
             * This Controller is a rather hacky way to use the Razor Engine
             * to create dynamically generated CSS files based on whatever computation we desire.
             * Originally described in: http://www.codeproject.com/Articles/171695/Dynamic-CSS-using-Razor-Engine
             * 
             * In this project, we attempt to stick with the MVC pattern as much as possible so
             * we only use some simple calculations in here, but it is entirely possible to do much more
             * since we're essencially allowing the execution of C# code inside the CSS file.
             * 
             * Also worth to note, don't expect Visual Studio to help you much with propper auto-complete
             * and all that other stuff while editing the CSS file since it dosn't understand that it has
             * the power of Razor with it.
             * 
             */

            Response.ContentType = "text/css";
            return RazorEngine.Razor.Parse(System.IO.File.ReadAllText(Server.MapPath("/Content/Site.css")));

        }

    }
}

bloGrid/Views/Home/Index.cshtml
@{
    ViewBag.Title = "bloGrid";
}

<div id="container">

    @RenderPage("_LoginBar.cshtml")


    @{
        if (ViewBag.Logged == true)
        {
            @RenderPage("_PanelBar.cshtml")
        }
    }

    @RenderPage("_Content.cshtml")
    @RenderPage("_Footer.cshtml")

</div>

bloGrid/Views/Home/_Content.cshtml
@using bloGrid.Helpers


<div id="Content">
        <div id="tumblelog">
            @{
                // Dynamic loading of panels from list of dictionaries
                // that are provided by the controller after parsing them from a
                // JSON object
                
                // Helper to call is determined by the value of type in each dictionary
                // further parameters are passed by looking them up in the dictionary 
                
                foreach (Dictionary<string, string> panel in ViewBag.Panels)
                {
                    if (panel["type"] == "facebook")
                    {
                        @Html.Facebook(panel["url"])
                    }
                    else if (panel["type"] == "instagram")
                    {
                        @Html.Instagram(panel["url"])
                    }
                    else if (panel["type"] == "youtube")
                    {
                        @Html.Youtube(panel["url"])
                    }
                    else if (panel["type"] == "rss")
                    {
                        @Html.Rss(panel["url"])
                    }
                    else if (panel["type"] == "twitter")
                    {
                        @Html.Twitter("chris_ctx")
                    }
                }
             }
        </div>
        @ViewBag.json
</div>

bloGrid/Views/Home/_Footer.cshtml
<div id="Footer">
    bloGrid  
</div>

bloGrid/Views/Home/_LoginBar.cshtml
@model bloGrid.Models.Account

<div id="LoginBar">
    @{
        <a href="/Home" id="Home">Home</a>
        if (ViewBag.Logged == true)
        {
            
            <a href="/Home/Delete" id="Restart">Delete all</a>
        }
        else
        {
            <a href="#" id="Edit">Edit</a>
        }
     }

    <div id="login">
        @using (Html.BeginForm("Edit", "Home", FormMethod.Post))
        {
            @Html.Label("Username: ")<br/>
            @Html.TextBoxFor(model => model.Name)<br/>
            @Html.Label("Password: ") <br/>
            @Html.PasswordFor(model => model.Password)<br/>
            <input type="submit" value="Login">
        }
     </div>
</div>

bloGrid/Views/Home/_PanelBar.cshtml
<div id="PanelsBar">

    <img src="~/Content/Images/border/facebook.png" class="panel" id="facebook"/>
    <img src="~/Content/Images/border/instagram.png" class="panel" id="instagram"/>
    <img src="~/Content/Images/border/rss.png" class="panel" id="rss"/>
    <img src="~/Content/Images/border/twitter.png" class="panel"/ id="twitter">
    <img src="~/Content/Images/border/youtube.png" class="panel" id="youtube"/>

</div>

bloGrid/Views/Shared/FailWhale.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FailWhale</title>
</head>
<body style="background-color: azure;">
    <div>
        Sorry, something went wrong and we will work to fix it.

        There are no fail whales here, this ain't twitter.
    </div>
</body>
</html>

bloGrid/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Action("Index", "Style")" type="text/css" rel="stylesheet">

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/jquery-ui-1.8.20.min.js")
</head>
<body>
     @RenderBody()
</body>

    @Scripts.Render("~/Scripts/jquery.masonry.min.js")

    @RenderSection("scripts", required: false)
    @Scripts.Render("~/Scripts/MasonryStart.js")
    @Scripts.Render("~/Scripts/DragDrop.js")
    @Scripts.Render("~/Scripts/LoginPanel.js")


</html>